server:
  port: 8082 #管理界面访问端口
spring:
  main:
    web-application-type: none #是否开启Tomcat;开启: servlet,关闭: none，关闭后无法使用web界面管理代理信息

vine:
  bind-port: 8523 #隧道监听端口，用于与客户端进行通信
  #代理配置文件存储地址
  proxy-path: /Users/liuxin/Desktop/vine/vine-server/src/main/resources/proxy.toml


