
[[clients]]
name = "客户端1" #客户端的名字 可以当作一个用户
secretKey = "4b0063baa5ae47c2910fc25265aae4b9" #客户端秘钥
status = 1 #客户端状态 1:在线 0:离线

[[clients.proxies]]
name = "mysql" #代理名称 自定义
type = "tcp" #代理类型 TCP HTTP UDP HTTPS 不区分大小写
localIP = "127.0.0.1" #内网IP地址 localhost/192.168.x.x/127.0.0.1
localPort = 3306 #内网服务的端口
remotePort = 3307 #暴露在公网的端口

[[clients.proxies]]
name = "redis"
type = "tcp"
localIP = "127.0.0.1"
localPort = 6379
remotePort = 6380

[[clients.proxies]]
name = "web"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
remotePort = 8085


#第二个客户端 用户2
[[clients]]
name = "客户端2"
secretKey = "7c0084cbb6bf58d3021fd36376bbf5c0"
status = 1

[[clients.proxies]]
name = "postgresql"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5432
remotePort = 5433

[[clients.proxies]]
name = "http"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8080
remotePort = 8081
