server:
  port: 8082 #管理界面访问端口
spring:
  main:
    web-application-type: none #是否开启Tomcat;开启: servlet,关闭: none，关闭后无法使用web界面管理代理信息
etp:
  console:
    enable: true #是否开启命令行管理终端,开启后可以远程交互式管理代理规则配置
    username: admin
    password: 123456
  bind-port: 8523 #隧道监听端口，用于与客户端进行通信
  #代理配置文件存储地址
  proxy-path: /Users/liuxin/Desktop/etp/etp-server/src/main/resources/proxy.toml


