bindPort=9527
[[clients]]
name = "windows"
secretKey = "4b0063baa5ae47c2910fc25265aae4b9" #客户端秘钥，自定义
status = 1 #客户端状态 1:在线 0:离线

[[clients.proxies]]
name = "mysql" #代理名称 自定义
type = "tcp" #代理类型 TCP HTTP 不区分大小写
localPort = 3306 #内网服务的端口
remotePort = 3307 #暴露在公网的端口

[[clients.proxies]]
name = "redis"
type = "tcp"
localPort = 6379
remotePort = 6380

[[clients.proxies]]
name = "web"
type = "tcp"
localPort = 8080
remotePort = 8085

#第二个客户端
[[clients]]
name = "MAC"
secretKey = "7c0084cbb6bf58d3021fd36376bbf5c0"
status = 1

[[clients.proxies]]
name = "postgre"
type = "tcp"
localPort = 5432
remotePort = 5433

[[clients.proxies]]
name = "http"
type = "tcp"
localPort = 8080
remotePort = 8081
